//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iOptics.rc
//
#define ID_UPDATE                       3
#define ID_SET_P                        4
#define ID_SET_Q                        5
#define ID_GET_P                        6
#define ID_GET_Q                        7
#define IDD_HOMO                        9
#define IDD_ABOUTBOX                    100
#define IDB_TOOLBOX                     106
#define ID_TOOLBOX                      106
#define IDR_MAINFRAME                   128
#define IDR_IVIEWETYPE                  129
#define IDD_FEC                         132
#define IDD_LDC                         133
#define ID_TOOLBOX_BASE                 601
#define ID_TOOLBOX_FEC                  601
#define ID_TOOLBOX_LDC                  602
#define ID_TOOLBOX_HOMO                 603
#define ID_TOOLBOX_4                    604
#define ID_TOOLBOX_5                    605
#define ID_TOOLBOX_6                    606
#define ID_TOOLBOX_MEASURE              607
#define ID_TOOLBOX_TOOGLE               611
#define ID_TOOLBOX_APPLY                612
#define ID_TOOLBOX_ZOOMIN               613
#define ID_TOOLBOX_ZOOMOUT              614
#define ID_TOOLBOX_GRIDE                615
#define ID_TOOLBOX_SAVE                 616
#define ID_TOOLBOX_LOAD                 617
#define ID_TOOLBOX_LAST                 620
#define IDC_CENTER_X                    1001
#define IDC_CENTERX_SPIN                1002
#define IDC_CENTER_Y                    1003
#define IDC_CENTERY_SPIN                1004
#define IDC_RADIUS_X                    1005
#define IDC_RADIUSX_SPIN                1006
#define IDC_RADIUS_Y                    1007
#define IDC_RADIUSY_SPIN                1008
#define IDC_PITCH                       1009
#define IDC_PITCH_SPIN                  1010
#define IDC_YAW                         1011
#define IDC_YAW_SPIN                    1012
#define IDC_ROLL                        1013
#define IDC_ROLL_SPIN                   1014
#define IDC_RADIO0                      1015
#define IDC_RADIO1                      1016
#define IDC_RADIO2                      1017
#define IDC_RADIO3                      1018
#define IDC_RADIO4                      1019
#define IDC_RADICAL_1                   1021
#define IDC_RADICAL1_SPIN               1022
#define IDC_RADICAL_2                   1023
#define IDC_RADICAL2_SPIN               1024
#define IDC_FOV                       1025
#define IDC_FOV_SPIN                  1026
#define IDC_ASPECT                       1027
#define IDC_ASPECT_SPIN                  1028
#define IDC_IN_CX                       1030
#define IDC_IN_CY                       1031
#define IDC_OUT_CX                      1032
#define IDC_OUT_CY                      1033
#define IDC_U0                          1034
#define IDC_U1                          1035
#define IDC_U2                          1036
#define IDC_U3                          1037
#define IDC_V0                          1038
#define IDC_V1                          1039
#define IDC_V2                          1040
#define IDC_V3                          1041
#define IDC_X0                          1042
#define IDC_X1                          1043
#define IDC_X2                          1044
#define IDC_X3                          1045
#define IDC_Y0                          1046
#define IDC_Y1                          1047
#define IDC_Y2                          1048
#define IDC_Y3                          1049
#define IDC_H00                         1050
#define IDC_H01                         1051
#define IDC_H02                         1052
#define IDC_H10                         1053
#define IDC_H11                         1054
#define IDC_H12                         1055
#define IDC_H20                         1056
#define IDC_H21                         1057
#define IDC_H22                         1058
#define ID_Menu                         3277
#define ID_VIEW_ZOOMIN                  32771
#define ID_VIEW_ZOOMOUT                 32772
#define ID_VIEW_Navigater               32773
#define ID_VIEW_Ruler                   32774
#define ID_VIEW_Gride                   32775
#define ID_VIEW_Mesh                    32776
#define ID_PROCESS_FEC                  32780
#define ID_PROCESS_LDC                  32781
#define ID_PROCESS_HOMO                 32782
#define ID_PROCESS_4                    32784
#define ID_PROCESS_5                    32785
#define ID_PROCESS_6                    32786
#define ID_PROCESS_7                    32787
#define ID_PROCESS_PREVIEW              32790
#define ID_PROCESS_APPLY                32791
#define ID_PROCESS_EXIT                 32792
#define ID_INDICATOR_COLOR              32800
#define ID_INDICATOR_POS                32801
#define ID_INDICATOR_ZOOM               32802
#define ID_INDICATOR_SIZE               32803
#define ID_FILE_SAVEAS                  32808
#define ID_FILE_S                       32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
